"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { SupportLink } from "@/components/SupportLink";

/**
 * The single source of truth for this page's date, in ISO form.
 *
 * Deliberately a hand-edited constant rather than anything read off the
 * clock: a policy that re-dates itself on every deploy tells the reader
 * nothing about when the terms actually changed, which is the one thing the
 * date is for.
 */
const LAST_UPDATED = "2026-09-22";

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

/** "2026-09-22" → "22 September 2026". Pure string work, no Date parsing. */
function formatIsoDate(iso: string): string {
  const [year, month, day] = iso.split("-");
  return `${Number(day)} ${MONTHS[Number(month) - 1]} ${year}`;
}

/**
 * Horizontal scroll container for a table too wide for a phone.
 *
 * `tabIndex={0}` is required, not decorative: WCAG 2.1.1 — and axe's
 * `scrollable-region-focusable` check, which the e2e suite runs against this
 * page — says a region that scrolls has to be reachable by keyboard, and a
 * plain `div` is not. The jsx-a11y rule that flags a tabbable non-interactive
 * element allows only `tabpanel`, so it is switched off here by name.
 */
function ScrollableTable({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    // eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex
    <div className="overflow-x-auto" tabIndex={0} role="region" aria-label={label}>
      {children}
    </div>
  );
}

const headingClass = "text-2xl font-bold mb-4 text-foreground";
const thClass =
  "border-b border-border px-3 py-2 text-left align-bottom text-sm font-semibold text-foreground";
const tdClass = "border-b border-border px-3 py-3 align-top text-sm";

/** Rows of the "What we collect and why" table. */
const COLLECTED: { data: string; source: string; why: string; kept: string }[] = [
  {
    data: "Account: your SoundCloud numeric id, username, display name and avatar URL",
    source: "SoundCloud, when you sign in",
    why: "To show who is signed in and to act on your account",
    kept: "While your account exists",
  },
  {
    data: "Sign-in tokens, encrypted",
    source: "SoundCloud OAuth",
    why: "To call the SoundCloud API on your behalf",
    kept: "While you are connected; deleted when you disconnect or delete your account",
  },
  {
    data: "Session cookie",
    source: "Set by us at sign-in",
    why: "To keep you signed in for 7 days",
    kept: "7 days",
  },
  {
    data: "Operation log: which tool you ran, when, how long it took, whether it succeeded, the SoundCloud ids of the tracks, playlists and users it touched, and your device type, browser and OS family (worked out from the browser's user-agent string; the raw string is not stored)",
    source: "Generated by us when you use a tool",
    why: "Reliability, abuse prevention, and understanding which tools people use",
    kept: "12 months",
  },
  {
    data: "Library cache: copies of your likes, playlists, followings, followers and reposts exactly as SoundCloud returns them",
    source: "SoundCloud, when you open a tool",
    why: "So large libraries load in seconds instead of minutes",
    kept: "7 days",
  },
  {
    data: "Growth tools history: the SoundCloud accounts you chose to follow or like, their public name, avatar and follower counts, whether they followed back, the label you gave the session, and the accounts you picked as inspiration for it (their names and ids)",
    source: "SoundCloud, when you run the Growth tools",
    why: "To show you your history and let you undo it",
    kept: "12 months",
  },
  {
    data: "Public track and playlist catalog: title, artist name and id, genre, duration, availability and public link for a track; title, owner id and track count for a playlist — for anything that passes through the tools",
    source: "SoundCloud public data",
    why: "To show availability, and to study — in aggregate, and only by the operator — which genres and artists the tools handle",
    kept: "While the service runs. It is not tied to your account, and it is not removed when you delete your account",
  },
  {
    data: "Library index and assistant drafts from an unreleased feature: copies of your likes and playlist tracks, and any messages you exchanged with the assistant",
    source: "You, when that feature was tested",
    why: "Left over from testing; no live tool reads or writes it",
    kept: "While your account exists; deleted with it",
  },
  {
    data: "Feedback you send in the app: your message, which tool you were on, and an email address if you choose to give one",
    source: "You",
    why: "To fix bugs, plan features, and reply if you asked us to",
    kept: "24 months",
  },
  {
    data: "Support email: whatever you write to us",
    source: "You",
    why: "To help you",
    kept: "In the mailbox until your question is resolved",
  },
];

/** Rows of the "Who else handles your data" table. */
const PROCESSORS: { service: string; processes: string; where: string }[] = [
  {
    service: "SoundCloud",
    processes:
      "Your account and every action you take through the tools. SoundCloud's own privacy policy applies to it.",
    where: "SoundCloud's servers",
  },
  {
    service: "Microsoft Azure",
    processes:
      "Hosts the app, the database, our secrets and our logs. Its request logs include your IP address for 30 days.",
    where: "US West",
  },
  {
    service: "Neon",
    processes:
      "Holds a copy of the database from before 20 September 2026, kept so we can roll back. It is deleted by the end of October 2026.",
    where: "US",
  },
  {
    service: "Google",
    processes: "Only the support mailbox, and only if you email us.",
    where: "Google's servers",
  },
  {
    service: "Buy Me a Coffee",
    processes:
      "Only if you click the link. Nothing from Buy Me a Coffee is loaded on this site.",
    where: "Their own site",
  },
];

export default function PrivacyPage() {
  return (
    <main
      id="main-content"
      tabIndex={-1}
      className="min-h-screen bg-background text-foreground focus:outline-none"
    >
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10 md:py-16">
        <article className="rounded-xl border border-border bg-surface p-6 sm:p-8 shadow-elevation-1 md:p-12 dark:glass-card">
          <div className="mb-6">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground transition hover:text-primary-text"
            >
              <ArrowLeft className="h-4 w-4" />
              Home
            </Link>
          </div>

          <h1 className="text-3xl md:text-4xl font-bold mb-6 text-foreground">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated {formatIsoDate(LAST_UPDATED)}
          </p>

          <div className="space-y-10 text-muted-foreground leading-relaxed">
            <section>
              <h2 className={headingClass}>Who we are and how to reach us</h2>
              <p>
                Track Toolkit is run by Cole Hackman, an individual, in the
                United States.
              </p>
              <p className="mt-3">
                If you have a question about this policy or about your data,
                email{" "}
                <SupportLink subject="Privacy question" />. We answer privacy
                requests within 30 days.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>What we collect and why</h2>
              <ScrollableTable label="What we collect and why">
                <table className="w-full min-w-[40rem] border-collapse text-left">
                  <thead>
                    <tr>
                      <th scope="col" className={thClass}>
                        Data
                      </th>
                      <th scope="col" className={thClass}>
                        Where it comes from
                      </th>
                      <th scope="col" className={thClass}>
                        Why
                      </th>
                      <th scope="col" className={thClass}>
                        Kept for
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {COLLECTED.map((row) => (
                      <tr key={row.data}>
                        <td className={`${tdClass} text-foreground`}>{row.data}</td>
                        <td className={tdClass}>{row.source}</td>
                        <td className={tdClass}>{row.why}</td>
                        <td className={tdClass}>{row.kept}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </ScrollableTable>
            </section>

            <section>
              <h2 className={headingClass}>What we do not collect</h2>
              <ul className="list-disc space-y-2 pl-6">
                <li>
                  Your SoundCloud password. Sign-in happens on SoundCloud&apos;s
                  own servers, so we never see it.
                </li>
                <li>
                  Your IP address in our database. Our host&apos;s request logs
                  do keep it for 30 days — see &ldquo;Who else handles your
                  data&rdquo; below.
                </li>
                <li>Audio files.</li>
                <li>Your private messages.</li>
                <li>Your comments.</li>
                <li>Payment details.</li>
              </ul>
              <p className="mt-4">
                We run no analytics or advertising scripts and set no
                third-party cookies.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>Cookies and browser storage</h2>
              <p>We set four cookies, all of them our own:</p>
              <ul className="list-disc space-y-2 pl-6 mt-3">
                <li>
                  <code className="text-foreground">session</code> — signed,
                  HttpOnly, 7 days. It is what keeps you signed in.
                </li>
                <li>
                  <code className="text-foreground">pkce_verifier</code>,{" "}
                  <code className="text-foreground">app_url</code> and{" "}
                  <code className="text-foreground">post_login_path</code> — 10
                  minutes, set only while you are signing in and cleared as soon
                  as sign-in finishes.
                </li>
              </ul>
              <p className="mt-4">
                Browser storage holds interface preferences — whether the
                sidebar is collapsed, light or dark theme, which tools you used
                recently, which announcements you have dismissed, which warnings
                you have acknowledged (the Growth risk notice), and whether the
                Chrome extension is installed — and, on the Downloads page, the
                download queue you build. All of that stays in your browser and
                is never sent to us.
              </p>
              <p className="mt-4">
                None of these track you across sites, which is why there is no
                cookie banner.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>Who else handles your data</h2>
              <ScrollableTable label="Who else handles your data">
                <table className="w-full min-w-[36rem] border-collapse text-left">
                  <thead>
                    <tr>
                      <th scope="col" className={thClass}>
                        Service
                      </th>
                      <th scope="col" className={thClass}>
                        What they process
                      </th>
                      <th scope="col" className={thClass}>
                        Where
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {PROCESSORS.map((row) => (
                      <tr key={row.service}>
                        <td className={`${tdClass} text-foreground font-medium`}>
                          {row.service}
                        </td>
                        <td className={tdClass}>{row.processes}</td>
                        <td className={tdClass}>{row.where}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </ScrollableTable>
              <p className="mt-4">
                We do not sell or share personal data, and we have no
                advertising partners.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>Where your data is stored</h2>
              <p>
                In the United States. If you use Track Toolkit from another
                country, your data is transferred to and processed there.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>How long we keep it</h2>
              <p>
                The &ldquo;Kept for&rdquo; column above is the full picture. Two
                things shorten it:
              </p>
              <ul className="list-disc space-y-2 pl-6 mt-3">
                <li>
                  Accounts with no sign-in for 24 months are deleted, including
                  everything keyed to them.
                </li>
                <li>
                  When you disconnect the app from your SoundCloud account, we
                  delete your tokens immediately and the rest of your data
                  within 7 days, unless you sign in again first.
                </li>
              </ul>
            </section>

            <section>
              <h2 className={headingClass}>Your choices and rights</h2>
              <ul className="list-disc space-y-3 pl-6">
                <li>
                  <strong className="text-foreground">
                    Download your data.
                  </strong>{" "}
                  Account page → &ldquo;Download my data&rdquo;. You get
                  everything keyed to your account as a JSON file.
                </li>
                <li>
                  <strong className="text-foreground">Disconnect.</strong> From
                  the Account page, or from SoundCloud → Settings → Connected
                  apps.
                </li>
                <li>
                  <strong className="text-foreground">
                    Delete your account.
                  </strong>{" "}
                  From the Account page. It happens immediately, it cannot be
                  undone, and it removes everything keyed to your account.
                  Catalog rows are not yours and stay.
                </li>
                <li>
                  <strong className="text-foreground">Ask us.</strong> Email us
                  to correct something, to object to the operation log, or about
                  anything else: <SupportLink subject="Privacy question" />.
                </li>
                <li>
                  <strong className="text-foreground">Complain.</strong> You can
                  complain to a data-protection authority where you live.
                </li>
              </ul>
              <p className="mt-4">
                These apply to everyone who uses Track Toolkit, wherever you
                are.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>Security</h2>
              <ul className="list-disc space-y-2 pl-6">
                <li>Your SoundCloud tokens are encrypted at rest with AES-256-GCM.</li>
                <li>Our secrets live in a managed vault, not in the code.</li>
                <li>The site and the API are HTTPS only.</li>
                <li>Session cookies are signed and HttpOnly.</li>
                <li>Writes that arrive from another website are rejected.</li>
              </ul>
            </section>

            <section>
              <h2 className={headingClass}>Children</h2>
              <p>
                Track Toolkit is not for anyone under 13. If you believe a child
                has given us data, email{" "}
                <SupportLink subject="Privacy question" /> and we will remove
                it.
              </p>
            </section>

            <section>
              <h2 className={headingClass}>Changes</h2>
              <p>
                When this policy changes, we post the new version here with the
                date it changed.
              </p>
              <ul className="list-disc space-y-2 pl-6 mt-3">
                <li>
                  <strong className="text-foreground">{LAST_UPDATED}</strong> —
                  Rewritten to describe the library cache, the public catalog,
                  feedback, retention periods, in-app export and disconnect;
                  analytics scripts removed.
                </li>
              </ul>
            </section>

            <section>
              <h2 className={headingClass}>SoundCloud</h2>
              <p>
                Track Toolkit is not affiliated with, endorsed by, or connected
                to SoundCloud. SoundCloud&apos;s own privacy policy governs your
                SoundCloud account.
              </p>
            </section>
          </div>
        </article>
      </div>
    </main>
  );
}
